### PR TITLE
Add initial functional tests

### PR DESCRIPTION
**Pull request by rabi**
jira: [OSPRH-5738](https://issues.redhat.com//browse/OSPRH-5738)

### CODE REVIEW

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
zuul job failed with `MountVolume.SetUp failed for volume "cert" : secret "bmo-webhook-server-cert" not foundrecheck`

**Comment by rabi** [comment]
recheck

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
