### PR TITLE
Check for Available BMHs

### PR DESCRIPTION
**Pull request by rabi**
There could be BMHs in other states and we should exclude those.

### CODE REVIEW

**Comment by rabi** [comment]
2023-12-26T01:12:39-0500 INFO Waiting for process with pid 7473 to finish.
2023-12-26T01:23:08-0500 DEBUG error: Curl error (28): Timeout was reached for http://mirror.its.dal.ca/pub/epel/9/Everything/x86_64/repodata/950dfaecea329378965c2bde2a96dc0aabec387c4246c9a52328e85a89bcd88d-primary.xml.gz [Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds] (http://mirror.its.dal.ca/pub/epel/9/Everything/x86_64/repodata/950dfaecea329378965c2bde2a96dc0aabec387c4246c9a52328e85a89bcd88d-primary.xml.gz).

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
