### PR TITLE
Update to use shared renovate config

### PR DESCRIPTION
**Pull request by abays**

### CODE REVIEW

**Comment by abays** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
"fatal: [localhost]: FAILED! => {\"changed\": false, \"msg\": \"Failure downloading https://golang.org/dl/go1.19.10.linux-amd64.tar.gz, Request failed: <urlopen error [Errno 101] Network is unreachable>\"}",

**Review by rabi — APPROVED** [review]
/lgtm

**Pull request merged**
