### PR TITLE
Build agent with golang 1.20

### PR DESCRIPTION
**Pull request by gibizer**

### CODE REVIEW

**Comment by gibizer** [comment]
@rebtoor I saw that you did the FIPS enabling for the operator. I'm not sure if at that point we intentionally ignored the FIPS enabling for the agent. I just noticed that the agent still used golang 1.19 so I bumped that to 1.20.

**Review by rebtoor — CHANGES_REQUESTED** [review]
Totally missed this one... sorry.

BTW, 
we should also add the build tags [1] otherwise the `check-payload` test will fail.

[1] https://github.com/openstack-k8s-operators/openstack-baremetal-operator/blob/5918cf3aefdf26a45e660144f0931f63726a6eca/Dockerfile#L15-L29

**Comment by rebtoor** [comment]
@gibizer i modified the Dockerfile to have `$GOBUILD_EXTRA_ENV_FLAGS` and `GO_BUILD_EXTRA_ARGS` rightly used during build.

**Review by rebtoor — APPROVED** [review]

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
