### PR TITLE
[DNM] testing content-provider fix

### PR DESCRIPTION
**Pull request by Sandeepyadav93**
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/278

### CODE REVIEW

**Comment by rabi** [comment]
recheck

**Comment by Sandeepyadav93** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Pull request closed without merging**
