### PR TITLE
Add agent builder to github workflows

### PR DESCRIPTION
**Pull request by leifmadsen**
Build the openstack-baremetal-operator-agent image using GitHub Action
workflow. This follows the same pattern as OSP director Operator.

Signed-off-by: Leif Madsen <lmadsen@redhat.com>

### CODE REVIEW

**Comment by leifmadsen** [comment]
Andrew noted today that it was found the agent image wasn't being built on a regular basis. I went looking at other examples and found that OSPdO also builds an agent image: https://github.com/openstack-k8s-operators/osp-director-operator/blob/master/.github/workflows/build-osp-director-operator.yaml#L113-L147

I just ended up copying the template and adjusting it to match. It's possible some other work may be required here, so I'm marking it as draft until someone with more knowledge about release pipeline upstream can review.

In OSPdO there are images passed to the bundle build script, but it uses a different script than what is used for this Operator, so I'm not sure if additional instructions are required. Any comments on that would be appreciated.

**Comment by dprince** [comment]
I like it. Could we verify that the newly built agent gets picked up by the bundle workflow and that it gets publish (in digest format) as part of the subsequent workflow? I think it should just work... just wanted to confirm all is well there.

**Comment by leifmadsen** [comment]
> I like it. Could we verify that the newly built agent gets picked up by the bundle workflow and that it gets publish (in digest format) as part of the subsequent workflow? I think it should just work... just wanted to confirm all is well there.

Yea that was my main concern... how to test it :)

I might have to see about creating the initial empty repositories under my personal quay.io account and try running the scripts and have it try pushing there as a validation from the fork. Otherwise, I don't really know how to test this without "Doing It Live".

**Comment by leifmadsen** [comment]
@dprince ok I setup my personal quay.io path with secrets on the repository and re-ran the GHA workflow. I found that the agent build and the bundle build ran in parallel, which seemed like a bit of a problem. I've setup a `uses` parameter so that the bundle build waits for the agent build to happen. That now works as I'd expected.

The one problem I can think of, is that if the agent build fails, then the bundle build would also fail. I'm not sure if that's an acceptable workflow or not.

Resulting artifacts got pushed here:

* https://quay.io/repository/lmadsen-redhat/openstack-baremetal-operator?tab=tags
* https://quay.io/repository/lmadsen-redhat/openstack-baremetal-operator-agent?tab=tags
* https://quay.io/repository/lmadsen-redhat/openstack-baremetal-operator-bundle?tab=tags
* https://quay.io/repository/lmadsen-redhat/openstack-baremetal-operator-index?tab=tags

I'm out of time for today, but tomorrow I'll try to extract the contents of the bundle/index and make sure everything found and used the appropriate agent image build that was created as part of the GHA workflow.

**Comment by leifmadsen** [comment]
I extracted the bundle today, and this was the contents of the `relatedImages` list:

```
  relatedImages:
    - image: quay.io/openstack-k8s-operators/openstack-baremetal-operator-agent@sha256:0201cdaee9e34c700aef28e57ce778c100d5fb4c166f229c483551cb9564cc33
      name: agent-image-url-default
    - image: registry.redhat.io/ubi9/httpd-24@sha256:80f1282b07b094831416c68373242d1fa17e118f39b190b95a47818cd28ff208
      name: apache-image-url-default
    - image: gcr.io/kubebuilder/kube-rbac-proxy@sha256:d99a8d144816b951a67648c12c0b988936ccd25cf3754f3cd85ab8c01592248f
      name: kube-rbac-proxy
    - image: quay.io/lmadsen-redhat/openstack-baremetal-operator@sha256:105d70440f138132736b5cbf7ea12b84f7a158aacd2a547ed6afd6fa31d577d7
      name: manager
    - image: quay.io/podified-antelope-centos9/edpm-hardened-uefi@sha256:4dc6035de9c4c56c943e408e8ddad8dbd565837cda62a6629d93dbbe3f4d2098
      name: os_container_image_url_default
    - image: quay.io/openstack-k8s-operators/openstack-baremetal-operator-agent@sha256:0201cdaee9e34c700aef28e57ce778c100d5fb4c166f229c483551cb9564cc33
      name: agent_image_url_default
    - image: registry.redhat.io/ubi9/httpd-24@sha256:80f1282b07b094831416c68373242d1fa17e118f39b190b95a47818cd28ff208
      name: apache_image_url_default
    - image: quay.io/podified-antelope-centos9/edpm-hardened-uefi@sha256:4dc6035de9c4c56c943e408e8ddad8dbd565837cda62a6629d93dbbe3f4d2098
      name: os-container-image-url-default
```

Looks like everything continues to build up with SHA hashes. Only the manager container image is replaced inline of the bundle, but that's probably just because of how the scripting works. I looked at the hash for the agent that's there, and it matches what is currently marked as `latest` tag.

**Review by abays — APPROVED** [review]
/lgtm

/hold
Waiting for @dprince to review again

**Review by dprince — APPROVED** [review]

**Pull request merged**
