### PR TITLE
Moving tests to ginkgo

### PR DESCRIPTION
**Pull request by jpodivin**
* Test framework was changed to ginkgo, in order to keep up simplify maintenance.
* Makefile build dependency constants were moved towards top of the file.
* Coverage statistics are now being computed for all modules

### CODE REVIEW

**Comment by jpodivin** [comment]
recheck

**Comment by jpodivin** [comment]
recheck

**Comment by jpodivin** [comment]
recheck

**Comment by jpodivin** [comment]
recheck

**Comment by jpodivin** [comment]
Failed on `Wait for OpenStack controlplane to be deployed _raw_params=oc wait OpenStackControlPlane ` with `timed out waiting for the condition on openstackcontrolplanes/openstack-galera-network-isolation`

recheck

**Comment by jpodivin** [comment]
recheck

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
